#https://argo-cd.readthedocs.io/en/release-1.8/user-guide/commands/argocd_app_manifests/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hipstershop-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/srikanthhg/hipstershop-helm.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
    chart: adservice
  # sourceType: Helm
  # path:
  # - adservice
  # - cartservice
  # - checkoutservice
  # - currencyservice
  # - emailservice
  # - frontend
  # - paymentservice
  # - productcatalogservice
  # - recommendationservice
  # - shippingservice 
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true               # Automatically prune resources not specified in Git
      selfHeal: true            # Automatically reconcile any differences between the desired and current state of the application.
