#https://argo-cd.readthedocs.io/en/release-1.8/user-guide/commands/argocd_app_manifests/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hipstershop-app01
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/srikanthhg/hipstershop-helm.git
    targetRevision: HEAD
    path: adservice
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true               # Automatically prune resources not specified in Git
      selfHeal: true            # Automatically reconcile any differences between the desired and current state of the application.
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hipstershop-app02
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/srikanthhg/hipstershop-helm.git
    targetRevision: HEAD
    path: cartservice
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hipstershop-app03
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/srikanthhg/hipstershop-helm.git
    targetRevision: HEAD
    path: checkoutservice
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hipstershop-app04
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/srikanthhg/hipstershop-helm.git
    targetRevision: HEAD
    path: currencyservice
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hipstershop-app05
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/srikanthhg/hipstershop-helm.git
    targetRevision: HEAD
    path: emailservice
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hipstershop-app06
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/srikanthhg/hipstershop-helm.git
    targetRevision: HEAD
    chart: frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hipstershop-app07
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/srikanthhg/hipstershop-helm.git
    targetRevision: HEAD
    path: paymentservice
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hipstershop-app08
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/srikanthhg/hipstershop-helm.git
    targetRevision: HEAD
    path: productcatalogservice
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hipstershop-app09
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/srikanthhg/hipstershop-helm.git
    targetRevision: HEAD
    path: recommendationservice
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hipstershop-app10
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/srikanthhg/hipstershop-helm.git
    targetRevision: HEAD
    path: shippingservice
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 

