#https://argo-cd.readthedocs.io/en/stable/user-guide/application-set/
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hipstershop-app
  namespace: argocd
spec:
  #goTemplate: true
  #goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: hipstershop-dev
        url: https://kubernetes.default.svc
      - cluster: hipstershop-prod
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{.cluster}}-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/srikanthhg/hipstershop-helm.git
        targetRevision: HEAD
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: '{{.url}}'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      sourceType: Helm
